### PR TITLE
Server must send CONNACK 0x01 if CONNECT contains unsupported version…

### LINKED ISSUE #132: Server must send CONNACK 0x01 if CONNECT contains unsupported version of protocol
*Expected behavior:* in accordance with section 3.1.2.2 of MQTT Spec (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) "The Server MUST respond to the CONNECT Packet with a CONNACK return code 0x01 (unacceptable protocol level) and then disconnect the Client if the Protocol Level is not supported by the Server" 

*Actual behavior:* connection is closed by the server without sending CONNACK. Can be checked with `TC_MQTT_BROKER_CONNACK_005` test case from Eclipse IoT-Testware MQTT Test Suite (https://iottestware.readthedocs.io/en/master/mqtt_test_suite.html). 

*Investigation details:* actual check of protocol version is done by `io.netty.handler.codec.mqtt.MqttVersion.fromProtocolNameAndLevel` which throws `MqttUnacceptableProtocolVersionException`.
It's picked by `io.vertx.mqtt.impl.MqttServerConnection.handleMessage` as a failed `DecoderResult` and pushed further through `chctx.pipeline().fireExceptionCaught(result.cause());`.
Finally it gets to `io.vertx.core.net.impl.VertxHandler.exceptionCaught` which closes the channel. It appears to me that `MqttServerConnection.handleMessage` is the right place to give the 
`MqttUnacceptableProtocolVersionException` special treatment and send `CONNACK` prior to closing the connection.

### PR DESCRIPTION
**Pull request by vietj**
… of protocol - fixes #132

### CODE REVIEW

File: src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java [hunk 1]
```diff
@@ -87,7 +90,17 @@ void handleMessage(Object msg) {
...
+        if (cause instanceof MqttUnacceptableProtocolVersionException) {
+
+          MqttMessage connack = MqttEndpointImpl.createConnack(
+            MqttConnectReturnCode.CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION,
+            false);
+          so.writeMessage(connack);
+          so.close();
+        } else {
+          chctx.pipeline().fireExceptionCaught(result.cause());
+        }
```
Comment (ppatierno) [inline src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: Thinking about this approach it's clear why you did that btw ...
The `connack` method in the `MqttEndpointImpl` already handles closing the connection if the returncode is not about connection accepted so we are duplicating the logic here.
It's also true that here we don't have an `MqttEndpoint` instance which is created later.
Anyway, in order to use the same logic, I would add a new ctor to the `MqttEndpointImpl` accepting just the `conn` parameter and then using the regular `connack` method on it to return the unacceptable protocol version error.
Wdyt?

Comment (vietj) [reply src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: I believe it cannot work because the message we receive is partially decoded as it is a `MqttMessage` instance that is not an  `MqttConnectMessage` instance (because it cannot be constructed with an invalid version protocol version) so we cannot really initialise the endpoint.

Comment (ppatierno) [reply src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: For this reason, I was talking about a new ctor where the `MqttEndpointImpl` is initialized just with the connection not with "will" information for example that we don't have of course.
Having an endpoint instance helps anyway to avoid code duplication.

Comment (vietj) [reply src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: to be honest this will be an artificial control flow to me, there is not much duplicated here

Comment (vietj) [reply src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: the code is pretty straightforward and is implemented according to the spec when the exception is actually available

Comment (vietj) [reply src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: I reworked the code to do like you said, my personal opinion is stil what I said above.

we need to get this merged soon for 3.8 release

File: src/main/java/io/vertx/mqtt/impl/MqttEndpointImpl.java [hunk 2]
```diff
@@ -122,6 +122,17 @@ public MqttEndpointImpl(NetSocketInternal conn, String clientIdentifier, MqttAut
...
+  public MqttEndpointImpl(NetSocketInternal conn) {
+    this.conn = conn;
+    this.clientIdentifier = null;
+    this.auth = null;
+    this.will = null;
+    this.isCleanSession = false;
+    this.protocolVersion = 0;
+    this.protocolName = null;
+    this.keepAliveTimeoutSeconds = 0;
+  }
```
Comment (ppatierno) [inline src/main/java/io/vertx/mqtt/impl/MqttEndpointImpl.java]: why not calling the other ctor passing the above parameters?

File: src/main/java/io/vertx/mqtt/impl/MqttEndpointImpl.java [hunk 3]
```diff
@@ -295,14 +306,19 @@ public MqttEndpointImpl exceptionHandler(Handler<Throwable> handler) {
     }
   }
 
-  private MqttEndpointImpl connack(MqttConnectReturnCode returnCode, boolean sessionPresent) {
+  static io.netty.handler.codec.mqtt.MqttMessage createConnack(MqttConnectReturnCode returnCode, boolean sessionPresent) {
```
Comment (ppatierno) [inline src/main/java/io/vertx/mqtt/impl/MqttEndpointImpl.java]: This method isn't needed anymore if we are going to create an `MqttEndpointImpl` instance so we can just call the `connack` method as before.

File: src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java [hunk 4]
```diff
@@ -87,8 +90,13 @@ void handleMessage(Object msg) {
 
       DecoderResult result = mqttMessage.decoderResult();
       if (result.isFailure()) {
-        chctx.pipeline().fireExceptionCaught(result.cause());
-        return;
+        Throwable cause = result.cause();
+        if (cause instanceof MqttUnacceptableProtocolVersionException) {
+          //
```
Comment (ppatierno) [inline src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: my idea was about creating the endpoint here and sending the message not change the overall logic of handleConnect. Doesn't it work easily?

**Comment by vietj** [comment]
@ppatierno updated according to review

File: src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java (hunk 1 above)
Comment (ppatierno) [reply src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: I think we had a misunderstanding I meant just:

```java
Throwable cause = result.cause();
if (cause instanceof MqttUnacceptableProtocolVersionException) {
    endpoint = new MqttEndpointImpl(so);
    endpoint.reject(MqttConnectReturnCode.CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION);
}
chctx.pipeline().fireExceptionCaught(result.cause());
return;
```
whitout changing anything else in the handleConnect but adding just a ctor for MqttEndpointImpl with so as parameter.

Comment (vietj) [reply src/main/java/io/vertx/mqtt/impl/MqttServerConnection.java]: it's not clear what I should do perhaps you can modify yourself the PR and the right commit ?
